server:
    port: ${PORT:8080}

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        initialization-mode: always
        initialize: true
        continue-on-error: true
        platform: postgres
        max-active: 3

    jpa:
        hibernate:
            ddl-auto: create-drop
            format_sql: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect