version: '3'

services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    networks:
      - auth
    ports:
      - "5432:5432"

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    networks:
      - auth
    ports:
      - "5433:5432"

  token-redis:
    container_name: token-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - auth

  stateless-auth-api:
    build: './stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - auth
    ports:
      - "8080:8080"
  stateless-any-api:
    build: './stateless/stateless-any-api'
    container_name: stateless-any-api
    environment:
      - PORT=8081
    networks:
      - auth
    ports:
      - "8081:8081"
networks:
  auth:
    driver: bridge